# Generated by Django 3.2.5 on 2021-07-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='checkin',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='checkout',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_person',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='purpose',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='password',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
