# Generated by Django 3.2.5 on 2021-07-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210708_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cnic',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
